server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@my.realwld.shop:1521:xe
    username: youtube
    password: gusdneorjs0808
    driver-class-name: oracle.jdbc.driver.OracleDriver



  jpa:
    hibernate:
      ddl-auto: none
      # create일 경우 다시 테이블 생성한다 디폴트는 none
      properties:
      hibernate:
         #show_sql: true
        format_sql: true



logging.level:
  org.hibernate.SQL: debug
  org:.hibernate.type: trace

